name: Gerar APK Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Android
        uses: android-actions/setup-android@v4

      - name: Configurar Godot
        uses: solarlabyrinth/action-setup-godot@v3
        with:
          version: 4.4.1-stable
          export-templates: true

      - name: Gerar APK
        run: |
          mkdir -p build
          godot --headless --path . --export-release "Android" build/SuddenMobile.apk

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: SuddenMobile-APK
          path: build/SuddenMobile.apk
